In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from bokeh.plotting import figure, save, show, ColumnDataSource
from bokeh.models import (GMapPlot, GMapOptions, ColumnDataSource,
                          Patch, Patches, Range1d, LogColorMapper,
                          HoverTool, PanTool, WheelZoomTool,
                          BoxSelectTool, SaveTool)
from bokeh.embed import components, autoload_static
from bokeh.resources import CDN
from bokeh.io import output_notebook
from bokeh.palettes import RdYlBu11 as palette
import geopandas as gpd
import pysal as ps

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin

### Summary
1. In order to figure out the interactivity, make a plot where only the time is used as a variable. I will have 801 census tracts, and only the true peak times, which are 9am (tod=36) for traffic to the Loop, and 6pm (tod=72) for traffic from the Loop, with dow=2 (Wednesday).

## Map

In [3]:
#read off the geometries
chi_map = gpd.read_file('Data/Boundaries - Census Tracts - 2010.geojson')

In [4]:
chi_map.head()

statefp10 name10 commarea_n         namelsad10 commarea      geoid10 notes  \
0        17   8424         44  Census Tract 8424       44  17031842400         
1        17   8403         59  Census Tract 8403       59  17031840300         
2        17   8411         34  Census Tract 8411       34  17031841100         
3        17   8412         31  Census Tract 8412       31  17031841200         
4        17   8382         28  Census Tract 8382       28  17031838200         

  tractce10 countyfp10                                           geometry  
0    842400        031  (POLYGON ((-87.62404799998049 41.7302169999839...  
1    840300        031  (POLYGON ((-87.6860799999848 41.82295600001154...  
2    841100        031  (POLYGON ((-87.62934700001182 41.8527970000265...  
3    841200        031  (POLYGON ((-87.68813499997718 41.8556909999909...  
4    838200        031  (POLYGON ((-87.66781999997529 41.8741839999791...

I only need 'geoid10' which is the full ID of the census tract, and the geometry.

In [5]:
chi_map = chi_map[['geoid10', 'geometry']]

In [6]:
chi_map.to_file('chi_map_test.shp')

In [7]:
chi_map = gpd.read_file('chi_map_test.shp').set_index('geoid10')

In [8]:
census_tracts = np.array(chi_map.index)

In [9]:
#'holiday', 'TMAX', 'PRCP', and 'SNOW' are 0
df_by_date = pd.DataFrame([[tract, 2, tod, 0, 0, 0, 0]
                           for tract in census_tracts
                          for tod in [36, 72]])

In [10]:
df_by_date.columns = ['geoid10', 'dow', 'tod', 'holiday',
                      'TMAX', 'PRCP', 'SNOW']

In [11]:
df_by_date.head()

geoid10  dow  tod  holiday  TMAX  PRCP  SNOW
0  17031842400    2   36        0     0     0     0
1  17031842400    2   72        0     0     0     0
2  17031840300    2   36        0     0     0     0
3  17031840300    2   72        0     0     0     0
4  17031841100    2   36        0     0     0     0

In [12]:
class DateOneHotEncoder(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.ohe = OneHotEncoder()
        
    def fit(self, X, y=None):
        X['date'] = (24*4*df_by_date['dow'] + df_by_date['tod'])
        self.ohe.fit(X[['date']])
        return self
    
    def transform(self, X):
        X['date'] = (24*4*df_by_date['dow'] + df_by_date['tod'])
        return self.ohe.transform(X[['date']])

In [13]:
class HolidayTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        return X[['holiday']]

In [14]:
class WeatherScaler(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.ss = StandardScaler()
        
    def fit(self, X, y=None):
        X_weather = X[['TMAX', 'PRCP', 'SNOW']]
        self.ss.fit(X_weather)
        return self
    
    def transform(self, X):
        X_weather = X[['TMAX', 'PRCP', 'SNOW']]
        return self.ss.transform(X_weather)

In [15]:
model_from = pickle.load(open('model_from.pkl', 'rb'))
model_to = pickle.load(open('model_to.pkl', 'rb'))

In [16]:
#multiply by 4 to get the result for the full hour
df_by_date['from'] = 4*model_from.predict(df_by_date)
df_by_date['to'] = 4*model_to.predict(df_by_date)

In [17]:
df_by_date.head()

geoid10  dow  tod  holiday  TMAX  PRCP  SNOW  date         from  \
0  17031842400    2   36        0     0     0     0   228   737.673156   
1  17031842400    2   72        0     0     0     0   264  1122.679437   
2  17031840300    2   36        0     0     0     0   228   737.673156   
3  17031840300    2   72        0     0     0     0   264  1122.679437   
4  17031841100    2   36        0     0     0     0   228   737.673156   

            to  
0  1212.540440  
1   772.756497  
2  1212.540440  
3   772.756497  
4  1212.540440

In [18]:
def getPolyCoords(row, geom, coord_type):
    """Returns the coordinates ('x' or 'y') of edges of a Polygon exterior"""

    # Parse the exterior of the coordinate
    exterior = row[geom].exterior

    if coord_type == 'x':
        # Get the x coordinates of the exterior
        return list( exterior.coords.xy[0] )
    elif coord_type == 'y':
        # Get the y coordinates of the exterior
        return list( exterior.coords.xy[1] )

In [19]:
chi_map['x'] = chi_map.apply(getPolyCoords, geom='geometry', coord_type='x', axis=1)
chi_map['y'] = chi_map.apply(getPolyCoords, geom='geometry', coord_type='y', axis=1)

In [20]:
chi_map['area'] = chi_map['geometry'].area

In [21]:
chi_map.head()

geometry  \
geoid10                                                          
17031842400  POLYGON ((-87.62404799998049 41.73021699998396...   
17031840300  POLYGON ((-87.6860799999848 41.82295600001154,...   
17031841100  POLYGON ((-87.62934700001182 41.8527970000265,...   
17031841200  POLYGON ((-87.68813499997718 41.85569099999095...   
17031838200  POLYGON ((-87.66781999997529 41.8741839999791,...   

                                                             x  \
geoid10                                                          
17031842400  [-87.62404799998049, -87.62404800002855, -87.6...   
17031840300  [-87.6860799999848, -87.68606600004208, -87.68...   
17031841100  [-87.62934700001182, -87.62934000001623, -87.6...   
17031841200  [-87.68813499997718, -87.68815799996442, -87.6...   
17031838200  [-87.6678199999753, -87.66768299998921, -87.66...   

                                                             y      area  
geoid10                                                                   
17031842400  [41.73021699998396, 41.7302030000071, 41.73018...  0.000213  
17031840300  [41.82295600001154, 41.82301899996352, 41.8233...  0.000090  
17031841100  [41.8527970000265, 41.85257599999823, 41.85199...  0.000124  
17031841200  [41.85569099999095, 41.85649500000819, 41.8569...  0.000068  
17031838200  [41.874183999979095, 41.87419500000664, 41.874...  0.000126

In [22]:
#df_by_date = df_by_date.drop(['geometry', 'x', 'y'], axis=1)

In [23]:
df_by_date = df_by_date.join(chi_map, on='geoid10')

In [24]:
df_by_date.head()

geoid10  dow  tod  holiday  TMAX  PRCP  SNOW  date         from  \
0  17031842400    2   36        0     0     0     0   228   737.673156   
1  17031842400    2   72        0     0     0     0   264  1122.679437   
2  17031840300    2   36        0     0     0     0   228   737.673156   
3  17031840300    2   72        0     0     0     0   264  1122.679437   
4  17031841100    2   36        0     0     0     0   228   737.673156   

            to                                           geometry  \
0  1212.540440  POLYGON ((-87.62404799998049 41.73021699998396...   
1   772.756497  POLYGON ((-87.62404799998049 41.73021699998396...   
2  1212.540440  POLYGON ((-87.6860799999848 41.82295600001154,...   
3   772.756497  POLYGON ((-87.6860799999848 41.82295600001154,...   
4  1212.540440  POLYGON ((-87.62934700001182 41.8527970000265,...   

                                                   x  \
0  [-87.62404799998049, -87.62404800002855, -87.6...   
1  [-87.62404799998049, -87.62404800002855, -87.6...   
2  [-87.6860799999848, -87.68606600004208, -87.68...   
3  [-87.6860799999848, -87.68606600004208, -87.68...   
4  [-87.62934700001182, -87.62934000001623, -87.6...   

                                                   y      area  
0  [41.73021699998396, 41.7302030000071, 41.73018...  0.000213  
1  [41.73021699998396, 41.7302030000071, 41.73018...  0.000213  
2  [41.82295600001154, 41.82301899996352, 41.8233...  0.000090  
3  [41.82295600001154, 41.82301899996352, 41.8233...  0.000090  
4  [41.8527970000265, 41.85257599999823, 41.85199...  0.000124

In [25]:
df_ratios = pd.read_csv('Data/Ratios.csv')

In [26]:
df_ratios['census_tract'] = df_ratios['census_tract'].apply(str)

In [27]:
df_ratios = df_ratios.set_index('census_tract')

In [28]:
#df_by_date = df_by_date.drop(['ratio_from', 'ratio_to', 'from_loop', 'to_loop'], axis=1)

In [29]:
df_by_date = df_by_date.join(df_ratios[['ratio_from', 'ratio_to']], on='geoid10').fillna(0)

In [30]:
df_by_date['from_loop'] = (df_by_date['from'] * df_by_date['ratio_from'])
df_by_date['to_loop'] = (df_by_date['to'] * df_by_date['ratio_to'])

In [31]:
df_by_date.head()

geoid10  dow  tod  holiday  TMAX  PRCP  SNOW  date         from  \
0  17031842400    2   36        0     0     0     0   228   737.673156   
1  17031842400    2   72        0     0     0     0   264  1122.679437   
2  17031840300    2   36        0     0     0     0   228   737.673156   
3  17031840300    2   72        0     0     0     0   264  1122.679437   
4  17031841100    2   36        0     0     0     0   228   737.673156   

            to                                           geometry  \
0  1212.540440  POLYGON ((-87.62404799998049 41.73021699998396...   
1   772.756497  POLYGON ((-87.62404799998049 41.73021699998396...   
2  1212.540440  POLYGON ((-87.6860799999848 41.82295600001154,...   
3   772.756497  POLYGON ((-87.6860799999848 41.82295600001154,...   
4  1212.540440  POLYGON ((-87.62934700001182 41.8527970000265,...   

                                                   x  \
0  [-87.62404799998049, -87.62404800002855, -87.6...   
1  [-87.62404799998049, -87.62404800002855, -87.6...   
2  [-87.6860799999848, -87.68606600004208, -87.68...   
3  [-87.6860799999848, -87.68606600004208, -87.68...   
4  [-87.62934700001182, -87.62934000001623, -87.6...   

                                                   y      area    ratio_from  \
0  [41.73021699998396, 41.7302030000071, 41.73018...  0.000213  1.067123e-07   
1  [41.73021699998396, 41.7302030000071, 41.73018...  0.000213  1.067123e-07   
2  [41.82295600001154, 41.82301899996352, 41.8233...  0.000090  2.598445e-05   
3  [41.82295600001154, 41.82301899996352, 41.8233...  0.000090  2.598445e-05   
4  [41.8527970000265, 41.85257599999823, 41.85199...  0.000124  1.166312e-03   

   ratio_to  from_loop   to_loop  
0  0.000000   0.000079  0.000000  
1  0.000000   0.000120  0.000000  
2  0.000005   0.019168  0.005487  
3  0.000005   0.029172  0.003497  
4  0.000223   0.860357  0.270874

Use density (rides/area) for plots.

In [32]:
df_by_date['from_loop_density'] = (df_by_date['from_loop'] / df_by_date['area'])
df_by_date['to_loop_density'] = (df_by_date['to_loop'] / df_by_date['area'])

Normalize these numbers by the maximum.

In [33]:
df_by_date['from_loop_density'] = 255*(df_by_date['from_loop_density'] / max(df_by_date['from_loop_density']))
df_by_date['to_loop_density'] = 255*(df_by_date['to_loop_density'] / max(df_by_date['to_loop_density']))

In [34]:
df_by_date.columns

Index(['geoid10', 'dow', 'tod', 'holiday', 'TMAX', 'PRCP', 'SNOW', 'date',
       'from', 'to', 'geometry', 'x', 'y', 'area', 'ratio_from', 'ratio_to',
       'from_loop', 'to_loop', 'from_loop_density', 'to_loop_density'],
      dtype='object')

In [35]:
# Create the color mapper
color_mapper = LogColorMapper(palette=palette)

# Make a ColumnDataSource
g_df = df_by_date[['geoid10', 'dow', 'tod', 'x', 'y', 'from_loop', 'to_loop',
                   'from_loop_density', 'to_loop_density']]

### Add Google Maps

In [36]:
google_api_key = 'AIzaSyB7XKt5IZGuihEgsWnnYTl8BPME8qtXgYc'

In [37]:
#map_options = GMapOptions(lat=41.88, lng=-87.62, map_type="roadmap", zoom=12)

#plot = GMapPlot(x_range=Range1d(), y_range=Range1d(), map_options=map_options)

#plot.api_key = google_api_key

In [38]:
#glyph = Patches(xs='x', ys='y', fill_alpha=0.5,
#               fill_color={'field': 'from_loop_density', 'transform': color_mapper},)
#gsource = ColumnDataSource(g_df[(g_df['dow'] == 1) & (g_df['tod'] == 72)])
#plot.add_glyph(gsource, glyph)

GlyphRenderer(id='3ef25d93-1403-48fc-adb8-798178eb3f2d', ...)

In [39]:
#hover = HoverTool(tooltips=[('census tract', "@geoid10"),
#                           ('total from Loop', "@from_loop")])

In [40]:
#plot.add_tools(hover, PanTool(), WheelZoomTool(), BoxSelectTool(), SaveTool())

In [41]:
#show(plot)

In [42]:
def makePlot(morning=True):
    """hour is given in integers from 0 to 23."""
    google_api_key = 'AIzaSyB7XKt5IZGuihEgsWnnYTl8BPME8qtXgYc'
    map_options = GMapOptions(lat=41.88, lng=-87.62, map_type="roadmap", zoom=12)
    plot = GMapPlot(x_range=Range1d(), y_range=Range1d(), map_options=map_options)
    plot.api_key = google_api_key
    
    color_mapper = LogColorMapper(palette=palette)
    if morning:
        glyph = Patches(xs='x', ys='y', fill_alpha=0.5,
               fill_color={'field': 'to_loop_density', 'transform': color_mapper},)
        gsource = ColumnDataSource(g_df[g_df['tod'] == 36])
        hover = HoverTool(tooltips=[('census tract', "@geoid10"),
                           ('total to Loop (hourly)', "@to_loop")])

    else:
        glyph = Patches(xs='x', ys='y', fill_alpha=0.5,
               fill_color={'field': 'from_loop_density', 'transform': color_mapper},)
        gsource = ColumnDataSource(g_df[g_df['tod'] == 72])
        hover = HoverTool(tooltips=[('census tract', "@geoid10"),
                           ('total from Loop (hourly)', "@from_loop")])
    plot.add_glyph(gsource, glyph)
    plot.add_tools(hover, PanTool(), WheelZoomTool(), BoxSelectTool(), SaveTool())
    show(plot)
    return None

In [43]:
makePlot(True)

## Line plot

We need average fares for the 36 major census tracts. Ignore the rest for the purpose of this plot. The other tracts make up less than 10% of all rides.

In [44]:
df_avg = pd.read_csv('GetAvg/stats_3.csv')

In [45]:
df_avg.head()

census_tract        avg       std
0   17031071400  11.324124  1.805734
1   17031071500   9.846077  1.586051
2   17031080100   8.630585  1.425377
3   17031080201   8.797396  1.306599
4   17031080202   8.287167  1.309778

Put the major census tracts in 4 distinct groups.

In [46]:
NORTH = ['17031071400', '17031071500', '17031080100', '17031080201',
         '17031080202', '17031080300', '17031081000', '17031081100',
         '17031081201', '17031081202', '17031081300', '17031081401',
         '17031081402', '17031081403', '17031081500', '17031081600',
         '17031081700', '17031081800', '17031842200']
         
WEST = ['17031243500', '17031280100', '17031281900', '17031833000',
        '17031833100', '17031838100', '17031841900', '17031842300',
        '17031980000']
        
LOOP = ['17031320100', '17031320400', '17031320600', '17031839000',
        '17031839100']
        
SOUTH =['17031330100', '17031841000', '17031980100']

In [47]:
def findDirection(row):
    """Assign group to each census tract."""
    tract = str(int(row['census_tract']))
    if tract in NORTH:
        return 'N'
    elif tract in WEST:
        return 'W'
    elif tract in LOOP:
        return 'L'
    else:
        return 'S'

In [48]:
df_avg['region'] = df_avg.apply(findDirection, axis=1)

In [49]:
df_avg['census_tract'] = df_avg['census_tract'].apply(str)

In [50]:
df_avg = df_avg.join(df_ratios[['ratio_from', 'ratio_to']], on='census_tract')

In [51]:
for item in df_avg[df_avg['region']=='N'][['avg', 'ratio_from', 'ratio_to']].values:
    print(item)

[  1.13241236e+01   4.99445630e-03   3.52539976e-03]
[  9.84607685e+00   9.62619745e-03   7.98933494e-03]
[  8.63058475e+00   7.05208308e-03   7.47243225e-03]
[  8.79739644e+00   2.67906593e-03   2.61466365e-03]
[  8.28716708e+00   5.16914435e-03   6.02757316e-03]
[  8.81705338e+00   6.84228667e-03   6.10838512e-03]
[ 7.49889426  0.00867315  0.00963972]
[  7.68806003e+00   7.01798849e-03   8.89583944e-03]
[ 7.61109364  0.03401044  0.0356376 ]
[ 8.03909664  0.00821333  0.00890366]
[ 7.67738973  0.0243486   0.02874784]
[ 7.15810992  0.03301161  0.0313799 ]
[ 7.40656487  0.01775213  0.01909883]
[ 6.52983036  0.04409529  0.0453716 ]
[ 6.49566784  0.05346543  0.07418738]
[ 6.19493159  0.02325757  0.0271815 ]
[ 6.12761999  0.05246585  0.05687428]
[ 6.62521538  0.03980929  0.03580569]
[  9.39590597e+00   5.96297723e-03   4.80998669e-03]


In [52]:
def traffic(region, fee=0, elasticity=0.5):
    if region == 'L': #no decrease for this
        return tuple(df_avg[df_avg['region']=='L'][['ratio_from', 'ratio_to']].sum())
    array = df_avg[df_avg['region']==region][['avg', 'ratio_from', 'ratio_to']].values
    total_from = 0
    total_to = 0
    for avg, ratio_from, ratio_to in array:
        #calculate the ratio of traffic decrease
        ratio = elasticity * (fee / avg)
        total_from += ratio_from * (1 - ratio)
        total_to += ratio_to * (1 - ratio)
    return total_from, total_to

In [53]:
total_from = sum([traffic(region)[0] for region in ['N', 'W', 'L', 'S']])

In [54]:
total_to = sum([traffic(region)[1] for region in ['N', 'W', 'L', 'S']])

In [55]:
def total_traffic(fee=0, elasticity=0.5):
    value_from = sum([traffic(region, fee, elasticity)[0]
                      for region in ['N', 'W', 'L', 'S']])
    value_to = sum([traffic(region, fee, elasticity)[1]
                      for region in ['N', 'W', 'L', 'S']])
    return value_from / total_from, value_to / total_to

In [56]:
x = np.linspace(0, 5, 51)

In [66]:
p_line = figure(plot_width=400, plot_height=400)

p_line.line(x, [total_traffic(fee=fee)[0] for fee in x],
            line_width=2)
p_line.line(x, [traffic('N', fee=fee)[0] for fee in x],
            line_width=2)
p_line.line(x, [traffic('W', fee=fee)[0] for fee in x],
            line_width=2)
p_line.line(x, [traffic('S', fee=fee)[0] for fee in x],
            line_width=2)
p_line.line(x, [traffic('L', fee=fee)[0] for fee in x],
            line_width=2)

show(p_line)

W-1001 (NO_DATA_RENDERERS): Plot has no data renderers: Figure(id='694e4eb6-a817-41ec-99ec-3000eefed8dd', ...)


In [2]:
from ipywidgets import interact

In [3]:
def f(x):
    return x

In [4]:
interact(f, x=10)

interactive(children=(IntSlider(value=10, description='x', max=30, min=-10), Output()), _dom_classes=('widget-interact',))

<function __main__.f>

In [5]:
interact(f, x=True)

interactive(children=(Checkbox(value=True, description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.f>

So what I need to do is to make a function where each parameter I feed to interact sets the parameters to make the graph.